### PR TITLE
Add ring when tag is selected

### PR DESCRIPTION
**Pull request by amirulabu**
Execution for idea #119

1. Preview what it looks like when tag is selected. [tailwind play](https://play.tailwindcss.com/2rDecYzP0A)

	<details><summary>Preview</summary>
	<p>
	
	Screenshot 2023-11-22 at 3 33 06 PM
	
	</p>
	</details> 

2. i am using current_page helper as per [docs](https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-current_page-3F)
3. I didn't run this in local (dev machine not setup for RoR dev), so no idea whether it works or not. 😅

### CODE REVIEW

**Comment by amree** [comment]
Sorry for taking too long to review this, but I just started to 'code' again 😅 

Btw, the current implementation requires changes:

```ruby
current_page?(controller: "map", tags: name.parameterize)
```

Let's take https://petakopi.my/map?tags=halal-certified for an example. In this case, `name` is equals to `Halal Certified`, not "halal-certified". By using `.parameterize`, we can 'slugify' the word automatically to match the query string.

I really need to get docker config to work to make it easy for people to contribute.

**Comment by amirulabu** [comment]
Changes are done, feel free to review again. 🙏 thank you

**Comment by amree** [comment]
Thanks for taking the time to work on this. Changes has been deployed 💪 

image

**Comment by amirulabu** [comment]
> Thanks for taking the time to work on this. Changes has been deployed 💪
> 
> image

oof, it overlaps in mobile. 😅 will attempt to fix once can run on local

**Pull request merged**
